name: Stg - Frontend

on:
  push:
    branches: [stg]
    paths:
      - 'frontend/**'
      - '.github/workflows/stg-frontend.yml'
      - '.github/workflows/reusable-frontend.yml'

permissions:
  id-token: write
  contents: read

jobs:
  frontend:
    name: Frontend - Staging
    uses: ./.github/workflows/reusable-frontend.yml
    with:
      environment: stg
      aws-region: eu-central-1
      node-version: '20'
      run-tests: false
    secrets: inherit