name: Stg - Backend

on:
  push:
    branches: [stg]
    paths:
      - 'app/**'
      - '.github/workflows/stg-backend.yml'
      - '.github/workflows/reusable-backend.yml'

jobs:
  backend:
    name: Backend - Staging
    uses: ./.github/workflows/reusable-backend.yml
    with:
      environment: stg
      aws-region: eu-central-1
      node-version: '20'
      run-tests: false
    secrets: inherit